version: "3.8"
services:
    db:
        image: mysql:latest
        restart: always
        command: --init-file /data/application/init.sql
        # https://stackoverflow.com/a/55706057
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE (problem was: "mbind: Operation not permitted")
        networks:
            - backend
        # TODO: use env_file or collect from environment variables
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - ./db/init.sql:/data/application/init.sql
            - ./db/config/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql

    notification-service:
        depends_on:
            - db
        build: ./notification
        networks:
            - backend
        ports:
            - "5000:5000"
        volumes:
            - ./notification:/usr/src/app


networks:
    backend:
        name: mysql-net
        driver: bridge
