"""init

Revision ID: 602dd97ec76a
Revises: 
Create Date: 2020-11-27 16:23:38.449237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602dd97ec76a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_order_supply_id'), 'order', ['supply_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_supply_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
