"""empty message

Revision ID: 65a86667fa27
Revises: 602dd97ec76a
Create Date: 2020-11-28 18:20:49.001641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65a86667fa27'
down_revision = '602dd97ec76a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_supply_id'), 'orders', ['supply_id'], unique=False)
    op.drop_index('ix_order_supply_id', table_name='order')
    op.drop_index('order_id', table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('supply_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`status` in (0,1))', name='order_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('order_id', 'order', ['order_id'], unique=True)
    op.create_index('ix_order_supply_id', 'order', ['supply_id'], unique=False)
    op.drop_index(op.f('ix_orders_supply_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
